### ISSUE TITLE
`act_dr6_lesing` likelihood as a  Python package, with data automatically downloaded by the setup.py

### ISSUE THREAD

**Issue by Uendert** [ACTCollaboration/act_dr6_lenslike#3]
Dear ACTCollaboration people,

First, thanks for such amazing data. I have a request/suggestion, if I may. Could you please make the `act_dr6_lesing` likelihood a Python Package, with data automatically downloaded by the setup.py?, or have the data installed by Cobaya as, e.g., for the Planck likelihood?

With regards,
Uendert

**Comment by itrharrison** [comment]
See #4 for the first part of this! Automated data download is for sure the next thing to do.

**Comment by itrharrison** [comment]
Just for my education... is there a preferred way of doing (or not doing) getting package data from a URL you are aware of?

From what I can read maybe the best way is for the package to include a command line script which goes and gets the data and installs it which the user can run when they want.

**Comment by cmbant** [comment]
use install_options class attribute, e.g. as 
https://github.com/CobayaSampler/cobaya/blob/master/cobaya/likelihoods/planck_2018_lowl/EE.py
Then you can just do cobaya-install packagename.LikeName
