### ISSUE TITLE
Allow generic_lnlike to return the theory and data vectors as well

### ISSUE THREAD

**Issue by joezuntz** [ACTCollaboration/act_dr6_lenslike#9]
For applications like Fisher, and debugging, it would be handy if generic_lnlike had an option to also return theory vectors, and maybe also the observed data vector and the covariance?

**Comment by itrharrison** [comment]
See https://github.com/ACTCollaboration/act_dr6_lenslike/tree/dev-return-theory which returns the binned, corrected theory to save.

**Comment by itrharrison** [comment]
See https://github.com/ACTCollaboration/act_dr6_lenslike/commit/3ae732761243c34d16300e30cdb065bb1f6e3dd3 which I accidentally just pushed to main 🙈.
